name: Smart Terminal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        
    - name: Debug information
      run: |
        poetry --version
        poetry config --list
        cat pyproject.toml
        
    - name: Install dependencies
      run: |
        poetry install --no-interaction --verbose